[server]
feature = { webui = true, tui = true }

# web控制台配置
[server.wui]
# web控制台监听端口
port = 9771
# web控制台监听地址
addr = [
    "0.0.0.0"
]

[server.wui.ca]
# 根证书
cert_ca = "/path/to/rootCA.crt"
# 服务端证书
cert_server = "/path/to/server.crt"
# 服务端密钥 严格保密
cert_key = "/path/to/server.key"

# tui控制台配置
[server.tui]
# tui控制台授权方式
feature = { ca = true, authorized_keys = true }
# tui控制台监听端口
port = 9772
# tui控制台监听地址
addr = [
    "0.0.0.0"
]

[server.tui.ca]
# 根证书
cert_ca = "/path/to/rootCA.crt"
# 服务端证书
cert_server = "/path/to/server.crt"
# 服务端密钥 严格保密
cert_key = "/path/to/server.key"

[server.tui.authorized_keys]
# 允许登入的公钥与其对应的用户
authorized_keys = [
    { user = "user", keys = "/path/to/user/authorized_keys" }
]
